spring:
  application:
    name: boletrix
  profiles:
    active: ${BOLETRIX_PROFILE:prod}
  web:
    locale: pt_BR
  flyway:
    enabled: true
    baseline-description: true
    locations: classpath:db/migration
